from .relationship import Relationship
from .collineation import Collineation
from .common_vertex_angle import CommonVertexAngle
from .n_angle_sector import NAngleSector
from .n_line_sector import NLineSector
from .opposite_vertical_angle import OppositeVerticalAngle
from .parallel import Parallel
from .perpendicular import Perpendicular
from .similar_triangle import SimilarTriangle
from .supplementary_angle import SupplementaryAngle
